export const weeklyBriefingsChatTitle = "Briefings";
export const weeklyBriefingsChatIdPrefix = "briefings-";
export const weeklyBriefingsChatDescription = "Read-only automated weekly briefings generated by the scheduled Worker.";

const readOnlyDescriptionMarker = "read-only automated weekly briefings";

export function briefingsChatIdForProject(projectId: string) {
  return `${weeklyBriefingsChatIdPrefix}${projectId}`;
}

export function isReservedBriefingsTitle(title: string | null | undefined) {
  return (title ?? "").trim().toLowerCase() === weeklyBriefingsChatTitle.toLowerCase();
}

export function isAutomatedBriefingsChat(
  chat: { id?: string | null; title?: string | null; description?: string | null } | null | undefined,
) {
  if (!chat) return false;
  const id = chat.id?.trim() ?? "";
  const title = chat.title?.trim() ?? "";
  const description = chat.description?.trim().toLowerCase() ?? "";
  return id.startsWith(weeklyBriefingsChatIdPrefix) || (isReservedBriefingsTitle(title) && description.includes(readOnlyDescriptionMarker));
}

export function assertMutableChatThread(
  chat: { id?: string | null; title?: string | null; description?: string | null } | null | undefined,
) {
  if (!isAutomatedBriefingsChat(chat)) return;
  throw new Error("Briefings is read-only. Weekly briefings are posted automatically by the scheduler.");
}
